# KITTI Dataset Configuration

data:
  dataset_type: kitti
  dataset_path: "/mnt/storage/Downloads/lidar_dataset/kitti/00"
  min_depth: 0.0
  max_depth: 80.0
  
  # Point Cloud Reader Options
  cloud_reader:
    cloud_format: bin
    bin_format: "<f4"
    cloud_folder: "${data.dataset_path}/velodyne"
    timestamp_filename: "${data.dataset_path}/times.txt"
    
  # Trajectory Reader (Ground Truth)
  trajectory_reader:
    reader_type: kitti
    filename: "${data.dataset_path}/pose.txt"
    gt_T_sensor_kitti_filename: "${data.dataset_path}/calib.txt"
    timestamp_dtol: 20
    
slam:
  # GICP / Tracking
  keyframe_th: 0.8
  knn_maxd: 99999.0
  max_correspondence_distance: 1.5
  overlapped_th: 0.895
  overlapped_th2: 0.005
  
  # 3DGS Mapping
  trackable_opacity_th: 0.01
  downsample_rate: 10
  keyframe_freq: 100
  n_trackable_keyframes: 10
  use_dynamic_fov: True
  
  # densify related parameters
  densify_threshold_opacity: 0.2
  densify_percentage: 0.40
  opt_scaling_max: 0.1
  use_densify: True
  densify_start_iteration: 100

  # pruning related parameters
  pruning_min_opacity: 0.05
  pruning_min_scale: 0.001

  # loss
  opt_lambda_dist : 0.01
  decay_speed: 0.0125
  loop_overlap_th: 0.7
  loop_constraint_noise: 1e-6
  loop_cooldown_time: 50.0
  downsample_voxel_size: 0.4
  
  # Sensor Intrinsics (Velodyne HDL-64E approx)
  W: 1024
  H: 64
  fov_x_deg: 360.0 # Horizontal FOV
  fov_y_deg: 26.8  # Vertical FOV
  depth_scale: 1.0
  depth_trunc: 80.0

# Output
output_path: output/kitti_result
verbose: True
demo: False
